insert into user (user_name, password, email, role, avatar_path, birth_date) values ('bart', 'myPass', 'bart@bart.com', 'ADMIN', 'http://dummyimage.com/214x100.png/ff4444/ffffff', '2019/01/02');
insert into user (user_name, password, email, role, avatar_path, birth_date) values ('kate', 'somethingPass', 'kate@usatoday.com', 'USER', 'http://dummyimage.com/234x100.pngmytrade/ff4444/ffffff', '2021/01/11');
insert into user (user_name, password, email, role, avatar_path, birth_date) values ('brailey', 'passtwo', 'brailey@poczta.pl', 'USER', 'http://dummyimage.com/238x100.png/cc0000/ffffff', '2017/02/25');
insert into user (user_name, password, email, role, avatar_path, birth_date) values ('mickey', 'payPass', 'bdunbabin3@businessinsider.com', 'USER', 'http://dummyimage.com/205x100.png/cc0000/ffffff', '2006/01/03');
insert into user (user_name, password, email, role, avatar_path, birth_date) values ('sebastian', 'sebPass', 'sebastian@delicious.com', 'USER', 'http://dummyimage.com/200x100.png/dddddd/000000', '2019/12/08');
insert into user (user_name, password, email, role, avatar_path, birth_date) values ('rob', 'passRob', 'rob@yahoo.co.jp', 'USER', 'http://dummyimage.com/180x100.png/ff4444/ffffff', '2011/06/29');
insert into user (user_name, password, email, role, avatar_path, birth_date) values ('bob', 'passingBy', 'bob@google.com.br', 'USER', 'http://dummyimage.com/103x100.png/dddddd/000000', '2018/02/13');
insert into user (user_name, password, email, role, avatar_path, birth_date) values ('aria', 'passAriapass', 'aria@google.com', 'USER', 'http://dummyimage.com/214x100.png/5fa2dd/ffffff', '2012/04/18');
insert into user (user_name, password, email, role, avatar_path, birth_date) values ('michael', 'jacksonPass', 'michael@jackson.com', 'USER', 'http://dummyimage.com/208x100.png/dddddd/000000', '2012/05/04');
insert into user (user_name, password, email, role, avatar_path, birth_date) values ('esther', 'estherPassGarden', 'esther@garden.com', 'USER', 'http://dummyimage.com/247x100.png/ff4444/ffffff', '2005/09/29');

insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (1, 'CLOTHES', 'Juice - Clamato, 341 Ml', 'http://dummyimage.com/227x100.png/5fa2dd/ffffff', 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi', 4118, 'Pensacola', '2021/02/17', '2021/08/01', false);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (1, 'BOOKS', 'Longos - Burritos', 'http://dummyimage.com/163x100.png/cc0000/ffffff', 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 8084, 'Xukou', '2021/07/30', '2020/10/22', false);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (1, 'CLOTHES', 'Cookies - Amaretto', 'http://dummyimage.com/211x100.png/ff4444/ffffff', 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', 7686, 'Ul', '2021/01/19', '2021/07/13', false);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (2, 'APPLIANCES', 'Dried Figs', 'http://dummyimage.com/234x100.png/5fa2dd/ffffff', 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros', 7466, 'Nueva Gorgona', '2021/05/04', '2021/04/24', true);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (3, 'CLOTHES', 'Napkin - Cocktail,beige 2 - Ply', 'http://dummyimage.com/246x100.png/ff4444/ffffff', 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi', 7673, 'Chemnitz', '2020/04/15', '2020/08/26', true);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (3, 'CLOTHES', 'Horseradish Root', 'http://dummyimage.com/236x100.png/5fa2dd/ffffff', 'quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc', 6807, 'Malawag', '2020/04/26', '2020/12/14', true);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (4, 'CLOTHES', 'Rice Pilaf, Dry,package', 'http://dummyimage.com/184x100.png/5fa2dd/ffffff', 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu', 8660, 'Kabongan Kidul', '2020/09/01', '2021/03/28', false);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (5, 'CLOTHES', 'Cookie Dough - Double', 'http://dummyimage.com/223x100.png/dddddd/000000', 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor', 2629, 'Ganta', '2020/06/14', '2021/01/10', true);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (5, 'CLOTHES', 'Venison - Ground', 'http://dummyimage.com/150x100.png/cc0000/ffffff', 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi', 2719, 'San Felipe', '2021/03/10', '2020/12/30', false);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (5, 'APPLIANCES', 'Oyster - In Shell', 'http://dummyimage.com/179x100.png/ff4444/ffffff', 'amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus', 2021, 'Putrajawa', '2020/03/27', '2020/10/29', true);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (6, 'BOOKS', 'Sultanas', 'http://dummyimage.com/241x100.png/ff4444/ffffff', 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus', 2366, 'Serra Talhada', '2021/06/22', '2020/08/16', true);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (7, 'BOOKS', 'Pork - Belly Fresh', 'http://dummyimage.com/107x100.png/5fa2dd/ffffff', 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', 7646, 'Onoda', '2020/12/02', '2021/07/22', true);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (8, 'CLOTHES', 'Veal - Shank, Pieces', 'http://dummyimage.com/101x100.png/5fa2dd/ffffff', 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo', 5689, 'Dąbie', '2020/10/12', '2020/12/31', true);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (9, 'CLOTHES', 'Ham - Virginia', 'http://dummyimage.com/167x100.png/ff4444/ffffff', 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante', 4785, 'Bodeh', '2020/04/02', '2020/10/24', true);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (10, 'CLOTHES', 'Pasta - Elbows, Macaroni, Dry', 'http://dummyimage.com/112x100.png/dddddd/000000', 'id consequat in consequat ut nulla sed accumsan felis ut at dolor quis', 7643, 'Kabac', '2020/03/01', '2020/09/06', false);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (10, 'CLOTHES', 'Water - Spring Water, 355 Ml', 'http://dummyimage.com/170x100.png/5fa2dd/ffffff', 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam', 3436, 'Jardim', '2021/07/22', '2021/02/15', false);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (10, 'CLOTHES', 'Cheese - Brick With Pepper', 'http://dummyimage.com/132x100.png/dddddd/000000', 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum', 8750, 'Karang Kulon', '2020/10/23', '2020/09/05', true);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (10, 'CLOTHES', 'Yogurt - Strawberry, 175 Gr', 'http://dummyimage.com/211x100.png/cc0000/ffffff', 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin', 5868, 'Lysekil', '2020/10/28', '2020/11/30', true);
insert into ad (owner_id, ad_category, title, image_path, description, price, city, created_date_time, modified_date_time, is_active) values (10, 'APPLIANCES', 'Carbonated Water - Wildberry', 'http://dummyimage.com/217x100.png/ff4444/ffffff', 'quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam', 1808, 'Issia', '2020/08/14', '2020/12/04', true);

SET FOREIGN_KEY_CHECKS=0;
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (1,1);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (1,2);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (1,3);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (2,4);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (3,5);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (3,6);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (4,7);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (5,8);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (5,9);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (5,10);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (6,11);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (7,12);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (8,13);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (9,14);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (10,15);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (10,16);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (10,17);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (10,18);
INSERT INTO user_ad_entity_list(user_entity_id,ad_entity_list_id) VALUES (10,19);
SET FOREIGN_KEY_CHECKS=1;

SET FOREIGN_KEY_CHECKS=0;
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (2,1);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (2,2);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (2,3);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (3,4);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (4,5);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (5,6);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (6,7);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (7,8);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (8,9);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (8,10);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (9,11);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (10,12);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (10,13);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (10,14);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (2,15);

INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (1,1);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (3,2);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (4,3);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (5,4);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (5,5);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (5,6);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (1,7);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (1,8);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (9,9);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (10,10);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (10,11);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (1,12);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (2,13);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (3,14);
INSERT INTO user_conversation_entity_list(user_entity_id,conversation_entity_list_id) VALUES (1,15);
SET FOREIGN_KEY_CHECKS=1;

insert into conversation (recipient_id, sender_id, title) values (2, 1, 'Versatile system-worthy policy');
insert into conversation (recipient_id, sender_id, title) values (3, 2, 'Open-architected incremental knowledge base');
insert into conversation (recipient_id, sender_id, title) values (4, 3, 'Exclusive reciprocal workforce');
insert into conversation (recipient_id, sender_id, title) values (5, 4, 'Exclusive intermediate open system');
insert into conversation (recipient_id, sender_id, title) values (6, 5, 'Implemented foreground moderator');
insert into conversation (recipient_id, sender_id, title) values (7, 6, 'Universal user-facing moratorium');
insert into conversation (recipient_id, sender_id, title) values (8, 7, 'Stand-alone uniform analyzer');
insert into conversation (recipient_id, sender_id, title) values (9, 8, 'Optimized client-server website');
insert into conversation (recipient_id, sender_id, title) values (10, 9, 'Innovative static database');
insert into conversation (recipient_id, sender_id, title) values (10, 1, 'Centralized disintermediate encryption');


insert into message (author_id, date_time, text, image_path) values (1, '2021/06/30', 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est', null);
insert into message (author_id, date_time, text, image_path) values (2, '2021/05/21', 'nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in', 'http://dummyimage.com/113x100.png/5fa2dd/ffffff');
insert into message (author_id, date_time, text, image_path) values (3, '2021/01/07', 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus', null);
insert into message (author_id, date_time, text, image_path) values (4, '2021/01/18', 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor', null);
insert into message (author_id, date_time, text, image_path) values (5, '2020/08/01', 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', null);
insert into message (author_id, date_time, text, image_path) values (6, '2020/11/21', 'eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', null);
insert into message (author_id, date_time, text, image_path) values (7, '2020/10/06', 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas', null);
insert into message (author_id, date_time, text, image_path) values (8, '2021/02/17', 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', null);
insert into message (author_id, date_time, text, image_path) values (9, '2020/10/29', 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit', null);
insert into message (author_id, date_time, text, image_path) values (10, '2021/01/30', 'diam in magna bibendum imperdiet nullam orci pede venenatis non', null);
insert into message (author_id, date_time, text, image_path) values (1, '2021/07/15', 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat', null);
insert into message (author_id, date_time, text, image_path) values (2, '2021/01/01', 'eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in', null);
insert into message (author_id, date_time, text, image_path) values (1, '2021/05/24', 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', null);
insert into message (author_id, date_time, text, image_path) values (1, '2021/05/15', 'suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique', null);
insert into message (author_id, date_time, text, image_path) values (1, '2021/08/02', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa', null);
insert into message (author_id, date_time, text, image_path) values (1, '2021/01/14', 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a', null);
insert into message (author_id, date_time, text, image_path) values (1, '2021/01/21', 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus', null);
insert into message (author_id, date_time, text, image_path) values (1, '2020/09/14', 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis', 'http://dummyimage.com/179x100.png/ff4444/ffffff');
insert into message (author_id, date_time, text, image_path) values (1, '2021/07/01', 'quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', null);
insert into message (author_id, date_time, text, image_path) values (1, '2021/05/16', 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula', null);
                                            
SET FOREIGN_KEY_CHECKS=0;                                                                                                    
insert into conversation_message_list (conversation_entity_id, message_list_id) values (1,1);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (2,2);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (3,3);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (4,4);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (5,5);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (6,6);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (7,7);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (8,8);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (9,9);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (10,10);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (10,11);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (10,12);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (10,13);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (1,14);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (1,15);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (1,16);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (10,17);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (10,18);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (10,19);
insert into conversation_message_list (conversation_entity_id, message_list_id) values (1,20);
SET FOREIGN_KEY_CHECKS=1;